<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FZLQPH2" name="Test.Sanity" tests="1" failures="0" timestamp="11 Feb 2020 15:51:20 GMT" time="0.000" errors="1">
  <testcase name="testSeller" time="0.000" classname="Test.Sanity">
    <error type="org.testng.TestNGException" message="
Data Provider public java.util.Map Test.Sanity.getDataFromDataprovider() throws java.lang.ClassNotFoundException,java.io.IOException,java.sql.SQLException must return either Object[][] or Iterator&lt;Object&gt;[], not interface java.util.Map">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.Map Test.Sanity.getDataFromDataprovider() throws java.lang.ClassNotFoundException,java.io.IOException,java.sql.SQLException must return either Object[][] or Iterator<Object>[], not interface java.util.Map
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- testSeller -->
</testsuite> <!-- Test.Sanity -->
